runtime: php55 
api_version: 1 

handlers: 
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(.+\.php)$
  script: \1
  
- url: /temperature
  script: temperature.php

- url: /rainfall
  script: rainfall.php

- url: /climate
  script: climate.php

- url: /.* 
  script: index.php